name: boundaries_detector
description: "Boundaries detector"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0-175.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image: ^4.3.0
  camera: ^0.11.0+2
  edge_vision:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/