name: edge_vision
description: "EdgeVision — A Flutter package for accurate and efficient object boundary detection. Capture clean contours and sharp edges effortlessly, making it ideal for applications like document scanning and object recognition. Simple to integrate, precise in action."
version: 0.0.1
homepage: https://alphamikle.dev

environment:
  sdk: ^3.6.0-175.0.dev

dependencies:
  image: ^4.3.0
  camera: ^0.11.0+2
  copy_with_extension: ^5.0.4
  equatable: ^2.0.5
  autoequal: ^0.9.1
  json_annotation: ^4.9.0
  isolator: ^2.0.8

dev_dependencies:
  test: ^1.25.8
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  copy_with_extension_gen: ^5.0.4
  autoequal_gen: ^0.9.1
  json_serializable: ^6.8.0
